(function(){
  'use strict';
  return new Promise((resolve, reject) => {
    let waitForBib = setInterval(() => {
      let itemBib = location.pathname.match(/\/bib\/(?<bib>\d+)/);
      let itemID = location.search.match(/itemid=(?<itemID>\d+)/);

      if (itemBib && itemBib.groups && itemBib.groups.bib &&
          itemID && itemID.groups && itemID.groups.itemID) {
        clearInterval(waitForBib);
        resolve({
          "itemBib": itemBib.groups.bib,
          "itemID": itemID.groups.itemID
        });
      }
    }, 350);
  }).then(res => {
    return new Promise((resolve, reject) => {
      let itemData = {
        "itemBib": res.itemBib,
        "itemID": res.itemID
      };

      let waitForCcode = setInterval(() => {
        const ccodes = {
          "ART": "AR",
          "BOOK/AUDIO-ENABLED JU": "BAEJ",
          "BOOK/AUDIO-ENABLED JU WORLD LANG": "BAEJWL",
          "BOOK/CD JU": "BCDJ",
          "BOOK/CASSETTE JU": "BCJ",
          "BOOK/DIGITAL AUDIO JU": "BDAPJ",
          "BOOKS AD FIC": "BKAFI",
          "BOOKS AD FIC CLASSICS": "BKAFICL",
          "BOOKS AD FIC CHRISTIAN": "BKAFICN",
          "BOOKS AD FIC FANTASY": "BKAFIFA",
          "BOOKS AD FIC GRAPHIC NOVELS": "BKAFIGN",
          "BOOKS AD FIC HISTORICAL": "BKAFIHI",
          "BOOKS AD FIC HOLIDAY": "BKAFIHL",
          "BOOKS AD FIC HORROR": "BKAFIHO",
          "BOOKS AD FIC SCID": "BKAFIID",
          "BOOKS AD FIC INSPIRATIONAL": "BKAFIIN",
          "BOOKS AD FIC MYSTERY": "BKAFIMY",
          "BOOKS AD FIC ROMANCE": "BKAFIRO",
          "BOOKS AD FIC SCIENCE FICTION": "BKAFISF",
          "BOOKS AD FIC SPANISH": "BKAFISP",
          "BOOKS AD FIC SUSPENSE": "BKAFISU",
          "BOOKS AD FIC THRILLER": "BKAFITH",
          "BOOKS AD FIC URBAN": "BKAFIUR",
          "BOOKS AD FIC WESTERNS": "BKAFIWE",
          "BOOKS AD FIC WORLD LANG": "BKAFIWL",
          "BOOKS AD GENEALOGY": "BKAGE",
          "BOOKS AD NFIC": "BKANF",
          "BOOKS AD NFIC ART": "BKANFAR",
          "BOOKS AD NFIC AUTOBIOGRAPHY": "BKANFAU",
          "BOOKS AD NFIC BUSINESS": "BKANFBU",
          "BOOKS AD NFIC BIOGRAPHY": "BKANFBY",
          "BOOKS AD NFIC COOKING": "BKANFCK",
          "BOOKS AD NFIC CRAFTS": "BKANFCR",
          "BOOKS AD NFIC EDUCATION": "BKANFED",
          "BOOKS AD NFIC GRAPHIC NOVELS": "BKANFGN",
          "BOOKS AD NFIC HEALTH": "BKANFHE",
          "BOOKS AD NFIC HOLIDAY": "BKANFHL",
          "BOOKS AD NFIC HOME": "BKANFHM",
          "BOOKS AD NFIC HISTORY": "BKANFHS",
          "BOOKS AD NFIC HOT TOPICS": "BKANFHT",
          "BOOKS AD NFIC SCID": "BKANFID",
          "BOOKS AD NFIC JOBS/CAREER": "BKANFJO",
          "BOOKS AD NFIC LOCAL MATERIALS": "BKANFLM",
          "BOOKS AD NFIC POPULAR CULTURE": "BKANFPC",
          "BOOKS AD NFIC RELIGION": "BKANFRE",
          "BOOKS AD NFIC SCIENCE": "BKANFSC",
          "BOOKS AD NFIC SELF-HELP": "BKANFSH",
          "BOOKS AD NFIC SPANISH": "BKANFSP",
          "BOOKS AD NFIC SPORTS": "BKANFSR",
          "BOOKS AD NFIC TRAVEL": "BKANFTL",
          "BOOKS AD NFIC WORLD LANG": "BKANFWL",
          "BOOKS AD RENTAL": "BKARN",
          "BOOKS JU BIG BOOKS": "BKJBG",
          "BOOKS JU FIC": "BKJFI",
          "BOOKS JU FIC PRIMARY (GR 1-4)": "BKJFI14",
          "BOOKS JU FIC AWARD WINNERS": "BKJFIAW",
          "BOOKS JU FIC BEGINNER": "BKJFIBE",
          "BOOKS JU FIC BILINGUAL": "BKJFIBI",
          "BOOKS JU FIC CHAPTER": "BKJFICH",
          "BOOKS JU FIC COMICS": "BKJFICO",
          "BOOKS JU FIC FANTASY": "BKJFIFA",
          "BOOKS JU FIC GRAPHIC NOVEL": "BKJFIGN",
          "BOOKS JU FIC MYSTERY": "BKJFIMY",
          "BOOKS JU FIC SCIENCE FICTION": "BKJFISF",
          "BOOKS JU FIC SPANISH": "BKJFISP",
          "BOOKS JU FIC WORLD LANG": "BKJFIWL",
          "BOOKS JU HOLIDAY": "BKJHL",
          "BOOKS JU NFIC": "BKJNF",
          "BOOKS JU NFIC PRIMARY (GR 1-4)": "BKJNF14",
          "BOOKS JU NFIC BILINGUAL": "BKJNFBI",
          "BOOKS JU NFIC BIOGRAPHY": "BKJNFBY",
          "BOOKS JU NFIC GRAPHIC NOVEL": "BKJNFGN",
          "BOOKS JU NFIC GRAPHIC NOVEL SPANISH": "BKJNFGNSP",
          "BOOKS JU NFIC SPANISH": "BKJNFSP",
          "BOOKS JU NFIC WORLD LANG": "BKJNFWL",
          "BOOKS YA FIC": "BKYFI",
          "BOOKS YA FIC CLASSICS": "BKYFICL",
          "BOOKS YA FIC COMICS": "BKYFICO",
          "BOOKS YA FIC FANTASY": "BKYFIFA",
          "BOOKS YA FIC GRAPHIC NOVEL": "BKYFIGN",
          "BOOKS YA FIC GRAPHIC NOVELS MANGA": "BKYFIGNMG",
          "BOOKS YA FIC MYSTERIES": "BKYFIMY",
          "BOOKS YA FIC SCIENCE FICTION": "BKYFISF",
          "BOOKS YA FIC WORLD LANG": "BKYFIWL",
          "BOOKS YA NFIC": "BKYNF",
          "BOOKS YA NFIC GRAPHIC NOVEL": "BKYNFGN",
          "BOOKS YA NFIC WORLD LANG": "BKYNFWL",
          "CASSETTES AD": "CAA",
          "CASSETTES JU": "CAJ",
          "COMPACT DISCS AD FIC": "CDAFI",
          "COMPACT DISCS AD SCID": "CDAID",
          "COMPACT DISCS AD MUSIC": "CDAMS",
          "COMPACT DISCS AD MUSIC SCID": "CDAMSID",
          "COMPACT DISCS AD NFIC": "CDANF",
          "COMPACT DISCS AD SPANISH": "CDASP",
          "COMPACT DISCS AD WORLD LANG": "CDAWL",
          "COMPACT DISCS JU FIC": "CDJFI",
          "COMPACT DISCS JU MUSIC": "CDJMS",
          "COMPACT DISCS JU NFIC": "CDJNF",
          "COMPACT DISCS JU WORLD LANG": "CDJWL",
          "COMPACT DISCS YA": "CDY",
          "DIGITAL AUDIO AD FIC": "DAPAFI",
          "DIGITAL AUDIO AD NFIC": "DAPANF",
          "DIGITAL AUDIO AD WORLD LANG": "DAPAWL",
          "DIGITAL AUDIO JU": "DAPJ",
          "DIGITAL AUDIO JU WORLD LANG": "DAPJWL",
          "DIGITAL AUDIO YA": "DAPY",
          "DVD BLU-RAY AD ANIME": "DBRAAN",
          "DVD BLU-RAY AD FEATURE": "DBRAFE",
          "DVD BLU-RAY AD FOREIGN FEATURE": "DBRAFF",
          "DVD BLU-RAY AD SCID": "DBRAID",
          "DVD BLU-RAY AD NON-FEATURE": "DBRANF",
          "DVD BLU-RAY AD RENTAL": "DBRARN",
          "DVD BLU-RAY AD TELEVISION SHOWS": "DBRATV",
          "DVD BLU-RAY JU": "DBRJ",
          "DVD AD ANIME": "DVDAAN",
          "DVD AD FEATURE": "DVDAFE",
          "DVD AD FOREIGN FEATURE": "DVDAFF",
          "DVD AD HOLIDAY": "DVDAHL",
          "DVD AD SCID": "DVDAID",
          "DVD AD NON-FEATURE": "DVDANF",
          "DVD AD RENTAL": "DVDARN",
          "DVD AD TELEVISION SHOWS": "DVDATV",
          "DVD AD WORLD LANG": "DVDAWL",
          "DVD JU FEATURE": "DVDJFE",
          "DVD JU HOLIDAY": "DVDJHL",
          "DVD JU NON-FEATURE": "DVDJNF",
          "DVD JU WORLD LANG": "DVDJWL",
          "DVD YA FEATURE": "DVDYFE",
          "ELECTRONIC RESOURCE": "ELR",
          "ELECTRONIC RESOURCE AUDIO": "ELRA",
          "ELECTRONIC RESOURCE MUSIC": "ELRM",
          "EQUIPMENT": "EQ",
          "EARLY READERS JU FIC": "ERJFI",
          "EARLY READERS JU NFIC": "ERJNF",
          "INTERLOAN": "IL",
          "KITS ADULT": "KTA",
          "KITS JUVENILE": "KTJ",
          "LARGE PRINT FIC": "LPFI",
          "LARGE PRINT FIC MYSTERIES": "LPFIMY",
          "LARGE PRINT FIC WESTERNS": "LPFIWE",
          "LARGE PRINT JU": "LPJ",
          "LARGE PRINT NFIC": "LPNF",
          "LARGE PRINT PICTURE BOOKS": "LPPB",
          "MAGAZINES AD": "MAA",
          "MAGAZINES AD WORLD LANG": "MAAWL",
          "MAGAZINES JU": "MAJ",
          "MAGAZINES YA": "MAY",
          "MICROFORM": "MF",
          "MAPS AD": "MPA",
          "PAPERBACKS AD FIC": "PAAFI",
          "PAPERBACKS AD FIC CLASSICS": "PAAFICL",
          "PAPERBACKS AD FIC FANTASY": "PAAFIFA",
          "PAPERBACKS AD FIC MYSTERY": "PAAFIMY",
          "PAPERBACKS AD FIC ROMANCE": "PAAFIRO",
          "PAPERBACKS AD FIC SCIENCE FIC": "PAAFISF",
          "PAPERBACKS AD FIC WESTERN": "PAAFIWE",
          "PAPERBACKS AD NFIC": "PAANF",
          "PAPERBACKS JU FIC": "PAJFI",
          "PAPERBACKS JU NFIC": "PAJNF",
          "PAPERBACKS YA FIC": "PAYFI",
          "PICTURE BOOKS JU BOARD BOOKS BILINGUAL": "PBJBBBI",
          "PICTURE BOOKS JU CONCEPT": "PBJCN",
          "PICTURE BOOKS JU FIC": "PBJFI",
          "PICTURE BOOKS JU FIC BOARD BOOKS": "PBJFIBB",
          "PICTURE BOOKS JU FIC BOARD BOOKS SPANISH": "PBJFIBBSP",
          "PICTURE BOOKS JU FIC BILINGUAL": "PBJFIBI",
          "PICTURE BOOKS JU FIC SPANISH": "PBJFISP",
          "PICTURE BOOKS JU FIC WORLD LANG": "PBJFIWL",
          "PICTURE BOOKS JU HOLIDAY": "PBJHL",
          "PICTURE BOOKS JU NFIC": "PBJNF",
          "PHONORECORDS": "PH",
          "SCORES": "SC",
          "SEEDS": "SEEDS",
          "SOFTWARE AD": "SOA",
          "SOFTWARE AD WORLD LANG": "SOAWL",
          "SOFTWARE JU": "SOJ",
          "TOYS": "TY",
          "VERTICAL FILE": "VF",
          "VIDEO GAMES AD": "VGA",
          "VIDEO GAMES JU": "VGJ",
          "VIDEO GAMES YA": "VGY",
          "VIDEO REC AD": "VRA",
          "VIDEO REC JU": "VRJ"
        };

        let title = document.querySelector('.item-circ-status .title');
        if (title) itemData.title = title.textContent.trim();

        let itemInfo = document.querySelectorAll("#item-" + res.itemID + " .item-block.item-info li");

        if (itemInfo) {
          for (let i of itemInfo) {
            if (i.getElementsByClassName('itemlabel')[0].textContent === "Collection:") {
              itemData.ccode = ccodes[i.getElementsByClassName('itemdata')[0].textContent];
              clearInterval(waitForCcode);
              resolve(itemData);
            }
          }
        }
      }, 350);
    });
  });
})();
